/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import static java.lang.Integer.valueOf;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;

import javax.swing.table.DefaultTableModel;

import crypto.AbsEvent;
import crypto.Event;
import crypto.EventCrypted;

/**
 *
 * @author Axel
 */

public class Diary extends javax.swing.JFrame {

	private DefaultTableModel model;
	protected ArrayList<AbsEvent> diary = new ArrayList<AbsEvent>();

	// sdjkg

	/**
	 * Creates new form Diary
	 * 
	 * @throws IOException
	 * @throws ClassNotFoundException
	 * @throws FileNotFoundException
	 */

	public Diary() throws FileNotFoundException, ClassNotFoundException,
			IOException {
		initComponents();
		//Memory.writeToFile(diary);
		diary = Memory.readFromFile();
		Iterator<AbsEvent> it = diary.iterator();
		while (it.hasNext()) {
			AbsEvent tmp = it.next();
			System.out.println(tmp);
			if (!tmp.isCrypted()) {
				Event tmp2 = (Event) tmp;
				model.addRow(new Object[] { tmp2.getName(),
						tmp2.getDescription(), tmp2.getDate().toString(),
						String.valueOf(tmp2.getLength()) });
			} else {
				EventCrypted tmp2 = (EventCrypted) tmp;
				// Crypter cr = new Crypter("password");
				// Event tmp3 = decryptEvent(tmp2);

			}
			// model.addRow(rowData);
		}
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * 
	 * @throws IOException
	 * @throws ClassNotFoundException
	 * @throws FileNotFoundException
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() throws FileNotFoundException,
			ClassNotFoundException, IOException {

		jScrollPane2 = new javax.swing.JScrollPane();
		agenda = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		year = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		eventName = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		description = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		month = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		hours = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		minute = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		cryptEvent = new javax.swing.JCheckBox();
		jLabel11 = new javax.swing.JLabel();
		month1 = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		hours1 = new javax.swing.JTextField();
		jLabel14 = new javax.swing.JLabel();
		minute1 = new javax.swing.JTextField();
		jLabel15 = new javax.swing.JLabel();
		year1 = new javax.swing.JTextField();
		day = new javax.swing.JTextField();
		day1 = new javax.swing.JTextField();
		jLabel16 = new javax.swing.JLabel();
		monthF = new javax.swing.JTextField();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		hoursF = new javax.swing.JTextField();
		jLabel19 = new javax.swing.JLabel();
		minuteF = new javax.swing.JTextField();
		jLabel20 = new javax.swing.JLabel();
		yearF = new javax.swing.JTextField();
		jLabel21 = new javax.swing.JLabel();
		dayF = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(0, 0, 204));
		setResizable(false);

		agenda.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {}, new String[] { "Name of Event",
						"Description", "Date", "Lenght" }));
		agenda.getColumnModel().getColumn(2).setPreferredWidth(200);
		agenda.getColumnModel().getColumn(1).setPreferredWidth(400);
		agenda.getColumnModel().getColumn(0).setPreferredWidth(100);
		agenda.setRowHeight(40);
		model = (DefaultTableModel) agenda.getModel();

		jScrollPane2.setViewportView(agenda);

		jButton1.setText("Add");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				try {
					jButton1MouseClicked(evt);
				} catch (FileNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		year.setToolTipText("");

		jLabel1.setBackground(new java.awt.Color(255, 0, 0));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel1.setText("Name of Event :");

		jLabel3.setBackground(new java.awt.Color(255, 0, 0));
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel3.setText("Date :");

		eventName.setToolTipText("");

		jLabel4.setBackground(new java.awt.Color(255, 0, 0));
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel4.setText("Description :");

		description.setToolTipText("");

		jLabel5.setBackground(new java.awt.Color(255, 0, 0));
		jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel5.setText("Year");

		month.setToolTipText("");

		jLabel6.setBackground(new java.awt.Color(255, 0, 0));
		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel6.setText("Month");

		jLabel7.setBackground(new java.awt.Color(255, 0, 0));
		jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel7.setText("Day");

		hours.setToolTipText("");

		jLabel8.setBackground(new java.awt.Color(255, 0, 0));
		jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel8.setText("Hours");

		minute.setToolTipText("");

		jLabel9.setBackground(new java.awt.Color(255, 0, 0));
		jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel9.setText("Minutes");

		jLabel10.setBackground(new java.awt.Color(255, 0, 0));
		jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel10.setText("Date of End");

		cryptEvent.setText("Crypt Event");

		jLabel11.setBackground(new java.awt.Color(255, 0, 0));
		jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel11.setText("Year");

		month1.setToolTipText("");

		jLabel12.setBackground(new java.awt.Color(255, 0, 0));
		jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel12.setText("Month");

		jLabel13.setBackground(new java.awt.Color(255, 0, 0));
		jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel13.setText("Day");

		hours1.setToolTipText("");

		jLabel14.setBackground(new java.awt.Color(255, 0, 0));
		jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel14.setText("Hours");

		minute1.setToolTipText("");

		jLabel15.setBackground(new java.awt.Color(255, 0, 0));
		jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel15.setText("Minutes");

		year1.setToolTipText("");

		day.setToolTipText("");

		day1.setToolTipText("");

		jLabel16.setBackground(new java.awt.Color(255, 0, 0));
		jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel16.setText("Year");

		monthF.setToolTipText("");

		jLabel17.setBackground(new java.awt.Color(255, 0, 0));
		jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel17.setText("Month");

		jLabel18.setBackground(new java.awt.Color(255, 0, 0));
		jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel18.setText("Day");

		hoursF.setToolTipText("");

		jLabel19.setBackground(new java.awt.Color(255, 0, 0));
		jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel19.setText("Hours");

		minuteF.setToolTipText("");

		jLabel20.setBackground(new java.awt.Color(255, 0, 0));
		jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel20.setText("Minutes");

		yearF.setToolTipText("");

		jLabel21.setBackground(new java.awt.Color(255, 0, 0));
		jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel21.setText("Search Date:");

		dayF.setToolTipText("");

		jButton2.setText("Find");
		jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton2MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane2,
						javax.swing.GroupLayout.DEFAULT_SIZE, 775,
						Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jLabel21,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										123,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jLabel16,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														53,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														yearF,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														53,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(26, 26, 26)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jLabel17,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														53,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														monthF,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														53,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(26, 26, 26)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														jLabel18,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														53,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														dayF,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														53,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(30, 30, 30)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jLabel19,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														53,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														hoursF,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														53,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jLabel20,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														53,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														minuteF,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														53,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(57, 57, 57)
								.addComponent(jButton2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										110,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jButton1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										94,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														jLabel3,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jLabel1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jLabel4,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														126,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														description,
														javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(eventName)))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(0,
																		0,
																		Short.MAX_VALUE)
																.addComponent(
																		jLabel10,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		126,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(76, 76,
																		76))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		cryptEvent)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel5,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						year,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(26, 26,
																		26)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel6,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						month,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(26, 26,
																		26)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jLabel7,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						day,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(30, 30,
																		30)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel8,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						hours,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel9,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						minute,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel11,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						year1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(26, 26,
																		26)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel12,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						month1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(26, 26,
																		26)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jLabel13,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						day1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(30, 30,
																		30)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel14,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						hours1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel15,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						minute1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						53,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGap(79, 79, 79)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jScrollPane2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										214,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(21, 21, 21)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel17,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		23,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		monthF,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(
																		layout.createSequentialGroup()
																				.addComponent(
																						jLabel19,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						23,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																								.addComponent(
																										hoursF,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addComponent(
																										dayF,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addComponent(
																		jLabel18,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		23,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jLabel21,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						30,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel16,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										23,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										yearF,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE))))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel20,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		23,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		minuteF,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(
														jButton2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addGap(57, 57, 57)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						30,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						eventName,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						28,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel4,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						30,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						description,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						28,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						30,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																								.addGroup(
																										layout.createSequentialGroup()
																												.addComponent(
																														jLabel6,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														23,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addPreferredGap(
																														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																												.addComponent(
																														month,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel5,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		23,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addComponent(
																																		year,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.PREFERRED_SIZE))
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel8,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		23,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.BASELINE)
																																				.addComponent(
																																						hours,
																																						javax.swing.GroupLayout.PREFERRED_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.PREFERRED_SIZE)
																																				.addComponent(
																																						day,
																																						javax.swing.GroupLayout.PREFERRED_SIZE,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						javax.swing.GroupLayout.PREFERRED_SIZE)))
																												.addComponent(
																														jLabel7,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														23,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addGroup(
																														javax.swing.GroupLayout.Alignment.TRAILING,
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel9,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		23,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addComponent(
																																		minute,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)))))
																.addGap(21, 21,
																		21)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel12,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										23,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										month1,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																								.addGroup(
																										layout.createSequentialGroup()
																												.addComponent(
																														jLabel11,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														23,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addPreferredGap(
																														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																												.addComponent(
																														year1,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGroup(
																										layout.createSequentialGroup()
																												.addComponent(
																														jLabel14,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														23,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addPreferredGap(
																														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																																.addComponent(
																																		hours1,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																		day1,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)))
																								.addComponent(
																										jLabel13,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										23,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGroup(
																										javax.swing.GroupLayout.Alignment.TRAILING,
																										layout.createSequentialGroup()
																												.addComponent(
																														jLabel15,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														23,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addPreferredGap(
																														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																												.addComponent(
																														minute1,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)))
																				.addComponent(
																						jLabel10,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						30,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		108,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		cryptEvent)
																.addGap(48, 48,
																		48)))
								.addContainerGap(31, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1MouseClicked(java.awt.event.MouseEvent evt)
			throws FileNotFoundException, IOException {// GEN-FIRST:event_jButton1MouseClicked
		Event eventCreated = new Event(eventName.getText(),
				description.getText(), new Date(), new Date());
		if (!cryptEvent.isSelected()) {


			model.addRow(new Object[] { eventName.getText(),
					description.getText(), new Date(), new Date() });
		}

		model.addRow(new Object[] {});
	}// GEN-LAST:event_jButton1MouseClicked

	private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton2MouseClicked
		Date d1 = giveDateFind();
		System.out.println(d1);
	}// GEN-LAST:event_jButton2MouseClicked

	private Date giveDateEvent() {
		Date d = new Date(valueOf(year.getText()),
				valueOf(month.getText()) - 1, valueOf(day.getText()),
				valueOf(hours.getText()), valueOf(minute.getText()));
		System.out.println(d);
		return d;
	}

	private Date giveDateFind() {
		Date d = new Date(valueOf(yearF.getText()),
				valueOf(monthF.getText()) - 1, valueOf(dayF.getText()),
				valueOf(hoursF.getText()), valueOf(minuteF.getText()));
		System.out.println(d);
		return d;
	}

	private Date giveDateEnd() {
		Date d = new Date(valueOf(year.getText()),
				valueOf(month.getText()) - 1, valueOf(day.getText()),
				valueOf(hours.getText()), valueOf(minute.getText()));
		System.out.println(d);
		return d;
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Diary.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Diary.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Diary.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Diary.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTable agenda;
	private javax.swing.JCheckBox cryptEvent;
	private javax.swing.JTextField day;
	private javax.swing.JTextField day1;
	private javax.swing.JTextField dayF;
	private javax.swing.JTextField description;
	private javax.swing.JTextField eventName;
	private javax.swing.JTextField hours;
	private javax.swing.JTextField hours1;
	private javax.swing.JTextField hoursF;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextField minute;
	private javax.swing.JTextField minute1;
	private javax.swing.JTextField minuteF;
	private javax.swing.JTextField month;
	private javax.swing.JTextField month1;
	private javax.swing.JTextField monthF;
	private javax.swing.JTextField year;
	private javax.swing.JTextField year1;
	private javax.swing.JTextField yearF;
	// End of variables declaration//GEN-END:variables
}
